---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: tls-options
spec:
  minVersion: VersionTLS12
  cipherSuites:
  - TLS_AES_128_GCM_SHA256
  - TLS_AES_256_GCM_SHA384
  - TLS_CHACHA20_POLY1305_SHA256
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security
spec:
  headers:
    frameDeny: true
    customResponseHeaders:
      Strict-Transport-Security: "max-age=31536000; includeSubdomains; preload"
      server: ""
    browserXssFilter: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: 'Host(`{{ .Values.paperless.host }}`)'
      priority: 10
      services:
        - name: paperless
          port: 8000
      middlewares:
        - name: http-to-https

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`{{ .Values.paperless.host }}`)'
      priority: 10
      services:
        - name: paperless
          port: 8000
      middlewares:
        - name: security
  tls:
    secretName: paperless-https-cert
    options:
      name: tls-options

