---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: paperless-ng-data-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.paperless.persistence.data.size }}
  storageClassName: {{ .Values.paperless.persistence.data.storageClass }}
