---
renovate:
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://gitea.os.v3nc.org/api/v1",
        "token": "<path:secret/data/k3s/renovate/gitea#token>",
        "autodiscover": "true",
        "printConfig": true,
        "redisUrl": "redis"
      }
