apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      kind: DaemonSet
    hostNetwork: true
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
    logs:
      general:
        level: INFO
      access:
        enabled: true
    additionalArguments:
      - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
    ports:
      web:
        proxyProtocol:
          trustedIPs:
            - 127.0.0.1/32
            - 10.11.12.0/24
        redirectTo: websecure
      websecure:
        proxyProtocol:
          trustedIPs:
            - 127.0.0.1/32
            - 10.11.12.0/24
      metrics:
        port: 9982
        hostPort: 9982
# See https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml for more examples
# The deployment.kind=DaemonSet and hostNetwork=true is to get real ip and x-forwarded for, and can be omitted if this is
# not needed.
