global:
  domains:
    alertmanager:
      host: alertmanager.os.v3nc.org
      service: kube-prome-alertmanager
      port: "9093"
    grafana:
      host: grafana.os.v3nc.org
      service: grafana
      port: "80"
    prometheus:
      host: prometheus.os.v3nc.org
      service: kube-prome-prometheus
      port: "9090"
