kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      # alertmanagerConfigNamespaceSelector:
      #   matchLabels:
      #     alertmanagerconfig: enabled

  grafana:
    defaultDashboardsTimezone: "Europe/Berlin"
    adminPassword: <path:secret/data/k3s/kube-prometheus/grafana#password>

  prometheus:
    prometheusSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      # serviceMonitorNamespaceSelector:
      #   matchLabels:
      #     alertmanagerconfig: enabled
      # podMonitorNamespaceSelector:
      #   matchLabels:
      #     alertmanagerconfig: enabled
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
