kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi

  grafana:
    adminPassword: <path:secret/data/k3s/kube-prometheus/grafana#password>

  prometheus:
    prometheusSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
