global:
  domains:
    alertmanager:
      host: alertmanager.ws.v3nc.org
      service: kube-prome-alertmanager
      port: "9093"
    grafana:
      host: grafana.ws.v3nc.org
      service: grafana
      port: "80"
    prometheus:
      host: prometheus.ws.v3nc.org
      service: kube-prome-prometheus
      port: "9090"
