global:
  domains:
    alertmanager:
      host: alertmanager.ws.v3nc.org
      port: "9093"
    grafana:
      host: grafana.ws.v3nc.org
      port: "80"
    prometheus:
      host: prometheus.ws.v3nc.org
      port: "9090"
