apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-https-cert
  labels:
    app.kubernetes.io/instance: argocd
spec:
  commonName: {{ .Values.global.hostname }}
  secretName: argocd-https-cert
  dnsNames:
    - {{ .Values.global.hostname }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
