---
global:
  domains:
    alertmanager:
      host: alertmanager.os.v3nc.org
      service: kube-prome-alertmanager
      port: "9093"
    grafana:
      host: grafana.os.v3nc.org
      service: grafana
      port: "80"
    prometheus:
      host: prometheus.os.v3nc.org
      service: kube-prome-prometheus
      port: "9090"

kube-prometheus-stack:
  alertmanager:
    config:
      route:
        group_by: ['namespace']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'telegram'
        routes:
          - receiver: 'telegram'
            matchers:
              - alertname !~ "InfoInhibitor|Watchdog"
          - receiver: 'null'
            matchers:
              - alertname =~ "InfoInhibitor|Watchdog"
      receivers:
        - name: 'null'
        - name: telegram
          telegram_configs:
            - bot_token: <path:secret/data/k3s/kube-prometheus/alertmanager#telegramApiToken>
              api_url: "https://api.telegram.org"
              chat_id: -816791813
              parse_mode: "HTML"

    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi

  grafana:
    defaultDashboardsTimezone: "Europe/Berlin"
    adminPassword: <path:secret/data/k3s/kube-prometheus/grafana#password>

  prometheus:
    prometheusSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
