---
securityContext:
  runAsUser: 1000

schedule: "*/15 * * * *"

shellCommand: gitea dump -c /data/gitea/conf/app.ini --type tar.gz -f /mnt/gitea-backup/gitea-os-$(date +%s)

volumes:
  - name: gitea-backup
    iscsi:
      targetPortal: 192.168.88.50
      iqn: iqn.2003-01.org.linux-iscsi.archlinux.x8664:sn.43fb4d620c83
      lun: 0
      fsType: ext4
      readOnly: false
      chapAuthDiscovery: false
      chapAuthSession: true
      secretRef:
        name: chap-secret
  - name: gitea-data
    persistentVolumeClaim:
      claimName: data-gitea-0

volumeMounts:
  - mountPath: /mnt/gitea-backup
    name: gitea-backup
  - mountPath: /mnt/gitea-data
    name: gitea-data

permissions:
  dir: /mnt/gitea-backup
  owner: "1000"
  group: "1000"

matchExpressions:
  - key: statefulset.kubernetes.io/pod-name
    operator: In
    values:
      - gitea-0

image: gitea/gitea:1.16.8-rootless
