---
# the user for your backup container
securityContext:
  # runAsUser: 1000

schedule: "0 0 * * *"

# example: mkdir -p /tmp/gitea && gitea dump -c /data/gitea/conf/app.ini --type tar.gz -f /mnt/gitea-backup/gitea-os-$(date +%s)
shellCommand: echo "update your shellCommand to backup && exit 1"

# add your source and target volumes
# volumes:
#  - name: gitea-backup
#    persistentVolumeClaim:
#      claimName: backup-gitea-0
#  - name: gitea-data
#    persistentVolumeClaim:
#      claimName: data-gitea-0

# add the mount paths to the defined volumes
# volumeMounts:
#   - mountPath: /mnt/gitea-backup
#     name: gitea-backup
#   - mountPath: /data
#     name: gitea-data

# the target have to be owned by the correct user
# if there is more than one dir to chown just apped it to the string
# permissions:
#   dirs: /mnt/gitea-backup
#   owner: "1000"
#   group: "1000"

# the backup job have to run on the same name as the pod
# matchExpressions: {}
#   - key: statefulset.kubernetes.io/pod-name
#     operator: In
#     values:
#       - gitea-0

# use the appropriate image containing your backup tool of choice
image: busybox
