apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-cinder-csi
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: ssh://git@g1tl4b.dynamic-dns.net:2222/venc0r/k8s-apps
    path: openstack-cinder-csi
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
    # plugin:
    #   name: kustomized-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openstack-cinder-csi
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
