resources:
  - all.yaml
patches:
  - path: kustomizations/controllerplugin-rbac.yaml
    target:
      kind: ClusterRole
      name: csi-attacher-role
  - path: kustomizations/nodeplugin-rbac.yaml
    target:
      kind: ClusterRole
      name: csi-nodeplugin-role
