openstack-cinder-csi:
  # Log verbosity level.
  # See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
  # for description of individual verbosity levels.
  logVerbosityLevel: 4
  storageClass:
    enabled: true
    delete:
      isDefault: false
      allowVolumeExpansion: true
    retain:
      isDefault: false
      allowVolumeExpansion: true
    custom: |-
      ---
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: csi
      provisioner: cinder.csi.openstack.org
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
