openstack-cinder-csi:
  # Log verbosity level.
  # See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
  # for description of individual verbosity levels.
  logVerbosityLevel: 4

  secret:
    enabled: true
    create: true
    name: cinder-csi-cloud-config
    data:
    # TODO wenns credentials gelöst sind muss das cloud.conf werden
      cloud-config: |-
        [Global]
        auth-url="https://de-nbg6-1.noris.cloud:5000/v3"
        username="jmarkert"
        user-domain-name="noris.de"
        password=""
        tenant-id=4dddce866d744599b947f3c18fd06be3
        tenant-name=jmarkert
        tenant-domain-name=noris.de
        # tenant-domain-id=0fd4315f3f784ee2a37cfd9657385fe5
        region=de-nbg6-1
  storageClass:
    enabled: true
    delete:
      isDefault: false
      allowVolumeExpansion: true
    retain:
      isDefault: false
      allowVolumeExpansion: true
    custom: |-
      ---
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: csi
      provisioner: cinder.csi.openstack.org
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      parameters:
        type: multiattach=<is> True
