---
renovate:
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://gitea.os.v3nc.org/api/v1",
        "token": "<path:secret/data/k3s/renovate/gitea#token>",
        "autodiscover": "true",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "printConfig": true,
        "redisUrl": "redis"
      }
  apiVersionOverrides:
    cronjob: 'batch/v1'
  redis:
    enabled: true
    global:
      storageClass: csi
