apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pacman-https-cert
spec:
  commonName: {{ .Values.pacman.domain }}
  secretName: pacman-https-cert
  dnsNames:
    - {{ .Values.pacman.domain }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
