apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pacman-https-cert
spec:
  commonName: pacman.k3s.v3nc.org
  secretName: pacman-https-cert
  dnsNames:
    - pacman.k3s.v3nc.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
