{{ if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end}}
{{ end }}
