apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-https-cert
spec:
  commonName: {{ .Values.vault.server.domain }}
  secretName: vault-https-cert
  dnsNames:
    - {{ .Values.vault.server.domain }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
