---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: vault-tls-backend
spec:
  serverName: vault.k3s.v3nc.org

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: 'Host(`vault.k3s.v3nc.org`)'
      priority: 10
      services:
        - name: vault
          port: 8200
          scheme: https
      middlewares:
      - name: http-to-https

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`vault.k3s.v3nc.org`)'
      priority: 10
      services:
        - name: vault
          port: 8200
          scheme: https
          serversTransport: vault-tls-backend
  tls:
    secretName: vault-https-cert
