apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@g1tl4b.dynamic-dns.net:2222/venc0r/k8s-apps
    path: gitea/manifests
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitea
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
