apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/k3s/gitea/admin"
data:
  username: <username|base64encode>
  password: <password|base64encode>
