gitea:
  persistence:
    storageClass: csi
  gitea:
    admin:
      existingSecret: gitea-admin-secret
      email: joerg.markert@gmail.com
    config:
      APP_NAME: "Gitea: Kaffee! und zwar schwarzer"
      RUN_MODE: prod
      server:
        SSH_PORT: 2222
        PROTOCOL: https
        DOMAIN: gitea.k3s.v3nc.org
        CERT_FILE: /gitea-https-cert/tls.crt
        KEY_FILE: /gitea-https-cert/tls.key
      security:
        PASSWORD_COMPLEXITY: spec
        MIN_PASSWORD_LENGTH: 8
      picture:
        DISABLE_GRAVATAR: true
    service:
      ssh:
        port: 2222
        externalIPs: 213.95.154.35
      database:
        PASSWD: <path:secret/data/k3s/gitea/pgsql#postgres-password>
  extraVolumes:
  - name: gitea-https-cert
    secret:
      secretName: gitea-https-cert
  extraVolumeMounts:
  - name: gitea-https-cert
    readOnly: true
    mountPath: /gitea-https-cert
  postgresql:
    enabled: true
    global:
      postgresql:
        postgresqlPassword: <path:secret/data/k3s/gitea/pgsql#postgres-password>
    persistence:
      size: 10Gi
      storageClass: csi
