---
backup:
  securityContext:
    runAsUser: 1000
  schedule: "0 6 * * *"
  shellCommand: mkdir -p /tmp/gitea && gitea dump -c /data/gitea/conf/app.ini --type tar.gz -f /mnt/gitea-backup/gitea-os-$(date +%s)
  volumeMounts:
    - mountPath: /mnt/gitea-backup
      name: gitea-backup
    - mountPath: /data
      name: gitea-data
  permissions:
    dirs: /mnt/gitea-backup
    owner: "1000"
    group: "1000"
  matchExpressions:
    - key: statefulset.kubernetes.io/pod-name
      operator: In
      values:
        - gitea-0
  image: gitea/gitea:1.17.3-rootless
  secret:
    name: iscsi-chap-secret
    data:
      node.session.auth.username: <path:secret/data/k3s/gitea/iscsi#username>
      node.session.auth.password: <path:secret/data/k3s/gitea/iscsi#password>

gitea:
  persistence:
    storageClass: csi
  image:
    rootless: true
  gitea:
    admin:
      existingSecret: gitea-admin-secret
      email: venc0r@live.com
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      APP_NAME: "Gitea: Kaffee! und zwar schwarzer"
      RUN_MODE: prod
      database:
        PASSWD: <path:secret/data/k3s/gitea/pgsql#postgres-password>
        LOG_SQL: false
      log:
        LEVEL: Error
      picture:
        DISABLE_GRAVATAR: true
      security:
        PASSWORD_COMPLEXITY: spec
        MIN_PASSWORD_LENGTH: 8
      server:
        SSH_PORT: 2222
        PROTOCOL: https
        CERT_FILE: /gitea-https-cert/tls.crt
        KEY_FILE: /gitea-https-cert/tls.key
      service:
        DISABLE_REGISTRATION: true
        DEFAULT_KEEP_EMAIL_PRIVATE: true
        DEFAULT_ORG_VISIBILITY: private
        DEFAULT_USER_IS_RESTRICTED: true
        REQUIRE_SIGNIN_VIEW: true
      repository:
        FORCE_PRIVATE: true
  service:
    ssh:
      port: 2222
      type: LoadBalancer
  extraVolumes:
  - name: gitea-https-cert
    secret:
      secretName: gitea-https-cert
  extraContainerVolumeMounts:
  - name: gitea-https-cert
    readOnly: true
    mountPath: /gitea-https-cert
  postgresql:
    enabled: true
    global:
      postgresql:
        postgresqlPassword: <path:secret/data/k3s/gitea/pgsql#postgres-password>
    persistence:
      size: 10Gi
      storageClass: csi
