gitea:
  persistence:
    storageClass: csi
  statefulset:
    annotations:
      avp.kubernetes.io/path: "secret/data/k3s/gitea/pgsql"
  gitea:
    admin:
      existingSecret: gitea-admin-secret
      email: joerg.markert@gmail.com
    # additionalConfigFromEnvs:
    # - name: ENV_TO_INI__DATABASE__USERNAME
    #   value: postgres
    # - name: ENV_TO_INI__DATABASE__DB_TYPE
    #   value: postgres
    # - name: ENV_TO_INI__DATABASE__NAME
    #   value: gitea
    # - name: ENV_TO_INI__DATABASE__PASSWD
    #   valueFrom:
    #     secretKeyRef:
    #       name: gitea-pgsql-secret
    #       key: postgres-password
    config:
      APP_NAME: "Gitea: Kaffee und zwar schwarzer"
      RUN_MODE: prod
      server:
        SSH_PORT: 2222
        PROTOCOL: https
        DOMAIN: gitea.k3s.v3nc.org
        CERT_FILE: /gitea-https-cert/tls.crt
        KEY_FILE: /gitea-https-cert/tls.key
      # security:
      #   PASSWORD_COMPLEXITY: spec
      service:
        ssh:
          port: 2222
      database:
        PASSWD: <postgres-password>
  extraVolumes:
  - name: gitea-https-cert
    secret:
      secretName: gitea-https-cert
  extraVolumeMounts:
  - name: gitea-https-cert
    readOnly: true
    mountPath: /gitea-https-cert
  postgresql:
    enabled: true
    global:
      postgresql:
        postgresqlPassword: <postgres-password>
    commonAnnotations: {}
    persistence:
      size: 10Gi
      storageClass: csi
