gitea:
  persistence:
    storageClass: csi
  gitea:
    admin:
      existingSecret: gitea-admin-secret
      email: joerg.markert@gmail.com
    additionalConfigFromEnvs:
    - name: ENV_TO_INI__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: pgsql-secret
          key: postges-password
    config:
      APP_NAME: "Gitea: Kaffee und zwar schwarzer"
      RUN_MODE: prod
      server:
        SSH_PORT: 2222
        PROTOCOL: https
        DOMAIN: gitea.k3s.v3nc.org
        CERT_FILE: /gitea-https-cert/tls.crt
        KEY_FILE: /gitea-https-cert/tls.key
      security:
        PASSWORD_COMPLEXITY: spec
      service:
        ssh:
          port: 2222
  extraVolumes:
  - name: gitea-https-cert
    secret:
      secretName: gitea-https-cert
  extraVolumeMounts:
  - name: gitea-https-cert
    readOnly: true
    mountPath: /gitea-https-cert
  postgresql:
    enabled: false
    # global:
    #   postgresql:
    #     auth:
    #       existingSecret: gitea-pgsql-secret
    # architecture: replication
    # replication:
    #   synchronousCommit: local
    # persistence:
    #   storageClass: csi
    # tls:
    #   enabled: false
    #   # autoGenerated: true
    #   # certificatesSecret: "pgsql-tls-secret"
    #   # certKeyFilename: "pgsql.key"
    #   # certFilename: "pgsql.crt"
    # volumePermissions:
    #   enabled: true
