gitea:
  persistence:
    storageClass: csi
  gitea:
    admin:
      existingSecret: gitea-admin-secret
      email: joerg.markert@gmail.com
    config:
      APP_NAME: "Gitea: Kaffee! und zwar schwarzer"
      RUN_MODE: prod
      database:
        PASSWD: <path:secret/data/k3s/gitea/pgsql#postgres-password>
      picture:
        DISABLE_GRAVATAR: true
      security:
        PASSWORD_COMPLEXITY: spec
        MIN_PASSWORD_LENGTH: 8
      server:
        SSH_PORT: 2222
        PROTOCOL: https
        CERT_FILE: /gitea-https-cert/tls.crt
        KEY_FILE: /gitea-https-cert/tls.key
      service:
        DISABLE_REGISTRATION: true
        DEFAULT_KEEP_EMAIL_PRIVATE: true
        DEFAULT_ORG_VISIBILITY: private
        DEFAULT_USER_IS_RESTRICTED: true
        REQUIRE_SIGNIN_VIEW: true
      repository:
        FORCE_PRIVATE: true
  service:
    ssh:
      port: 2222
      externalIPs: ['213.95.154.35']
      type: LoadBalancer
  extraVolumes:
  - name: gitea-https-cert
    secret:
      secretName: gitea-https-cert
  extraVolumeMounts:
  - name: gitea-https-cert
    readOnly: true
    mountPath: /gitea-https-cert
  postgresql:
    enabled: true
    global:
      postgresql:
        postgresqlPassword: <path:secret/data/k3s/gitea/pgsql#postgres-password>
    persistence:
      size: 10Gi
      storageClass: csi
