apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  type: Opaque
  annotations:
    avp.kubernetes.io/path: "secret/data/k3s/gitea/admin"
data:
  username: <username>
  password: <password>
