nextcloud:
  deploymentAnnotations:
    avp.kubernetes.io/path: kv/data/k3s/argocd/nextcloud

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 4G

  nextcloud:
    existingSecret:
      enabled: true
      secretName: nextcloud-secrets
      usernameKey: username
      passwordKey: password
      tokenKey: serverinfo_token

  internalDatabase:
    enabled: false

  externalDatabase:
    enabled: true
    type: mysql
    existingSecret:
      enabled: true
      secretName: nextcloud-secrets
      usernameKey: mysql_username
      passwordKey: mysql_password

  mariadb:
    enabled: true
    auth:
      username: <path:kv/data/k3s/argocd/nextcloud#mysql_username>
      password: <path:kv/data/k3s/argocd/nextcloud#mysql_password>
    architecture: standalone
    primary:
      persistence:
        enabled: true

  redis:
    enabled: true
    auth:
      password: <path:kv/data/k3s/argocd/nextcloud#redis_password>

  cronjob:
    enabled: true

  persistence:
    enabled: true

    nextcloudData:
      enabled: true

  rbac:
    enabled: true
