---
apiVersion: v1
kind: Endpoints
metadata:
  name: paperless
subsets:
- addresses:
  - ip: {{ .Values.paperless.ip }}
  ports:
  - name: paperless
    port: {{ .Values.paperless.port }}
    protocol: TCP
