---
apiVersion: v1
kind: Service
metadata:
  name: paperless
spec:
  ports:
  - name: paperless
    port: 80
    protocol: TCP
    targetPort: {{ .Values.paperless.port }}
  clusterIP: None
  type: ClusterIP
