kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: b2831dc4-6db9-2747-e166-9b7d4c209c01
  AVP_SECRET_ID: e067e5f0-67fe-471d-ac5b-5b9745a4c7a1
  AVP_TYPE: vault
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
