apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tmate.fullname" . }}
  labels:
    {{- include "tmate.labels" . | nindent 4 }}
data:
  hostname: {{ .Values.configMap.hostname }}
  websocket_base_url: {{ .Values.configMap.websocket_base_url }}
  master_base_url: {{ .Values.configMap.master_base_url }}
  user_facing_base_url: {{ .Values.configMap.user_facing_base_url }}
