apiVersion: v1
kind: Service
metadata:
  name: {{ include "tmate.fullname" . }}-master
  labels:
    {{- include "tmate.labels" . | nindent 4 }}
    {{ include "tmate.master.selectorLabels" . | nindent 4 }}

spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tmate.master.selectorLabels" . | nindent 4 }}
