apiVersion: v1
kind: Service
metadata:
  name: {{ include "tmate.fullname" . }}-sessions
  labels:
    {{- include "tmate.labels" . | nindent 4 }}
    {{ include "tmate.sessions.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.sessions.services.type }}
  ports:
    - port: {{ .Values.sessions.services.ssh.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
    - port: {{ .Values.sessions.services.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tmate.sessions.selectorLabels" . | nindent 4 }}
