apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: ssh://git@g1tl4b.dynamic-dns.net:2222/venc0r/k8s-apps
    path: vault
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
    # plugin:
    #   name: kustomized-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: "*"
      kind: "MutatingWebhookConfiguration"
      jsonPointers:
      - /webhooks/0/clientConfig/caBundle
