vault:
  server:
    auditStorage:
      enabled: true
      storageClass: csi
      size: 2Gi
    ha:
      enabled: true
      config: |
        ui = false

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "consul" {
          path = "vault"
          address = "HOST_IP:8500"
        }

        service_registration "kubernetes" {}
    dataStorage:
      enabled: true
      size: 2Gi
      storageClass: csi
