vault:
  global:
    tlsDisable: true
  server:
    auditStorage:
      enabled: true
      storageClass: csi
      size: 2Gi
    extraVolumes:
    - type: secret
      name: vault-https-cert
    ha:
      enabled: true
      config: |
        ui = false

        listener "tcp" {
          tls_disable = "false"
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-server-cert/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-server-cert/tls.key"
        }
        storage "consul" {
          path = "vault"
          address = "HOST_IP:8500"
        }

        service_registration "kubernetes" {}
    dataStorage:
      enabled: true
      size: 2Gi
      storageClass: csi
