apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-https-cert
spec:
  commonName: {{ .Values.gitea.gitea.server.DOMAIN }}
  secretName: gitea-https-cert
  dnsNames:
    - {{ .Values.gitea.gitea.server.DOMAIN }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
