---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: gitea-tls-backend
spec:
  serverName: gitea.k3s.v3nc.org

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: 'Host(`gitea.k3s.v3nc.org`)'
      priority: 10
      services:
        - name: gitea-http
          port: 3000
          scheme: https
      middlewares:
      - name: http-to-https

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`gitea.k3s.v3nc.org`)'
      priority: 10
      services:
        - name: gitea-http
          port: 3000
          serversTransport: gitea-tls-backend
          scheme: https
      middlewares:
      - name: http-to-https
  tls:
    secretName: gitea-https-cert

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitea-ssh
spec:
  entryPoints:
    - ssh
  routes:
    - match: 'Host(`gitea.k3s.v3nc.org`)'
      priority: 10
      services:
        - name: gitea-ssh
          port: 2222
