argo-cd:
  redis-ha:
    enabled: true

  controller:
    replicas: 1

  server:
    replicas: 2
    configEnabled: true
    config:
      sshConfigs: |
        Host gitea.os.v3nc.org
            KexAlgorithms ecdh-sha2-nistp521
            PubkeyAcceptedAlgorithms +ssh-rsa
        Host gitea.ws.v3nc.org
            KexAlgorithms ecdh-sha2-nistp521
            PubkeyAcceptedAlgorithms +ssh-rsa
        Host gitea.os.sh4ke.rocks
            KexAlgorithms ecdh-sha2-nistp521
            PubkeyAcceptedAlgorithms +ssh-rsa
        Host gitea.ws.sh4ke.rocks
            KexAlgorithms ecdh-sha2-nistp521
            PubkeyAcceptedAlgorithms +ssh-rsa
      configManagementPlugins: |
        - name: kustomized-helm
          init:
            command: ["/bin/sh", "-c"]
            args: ["helm dependency build || true"]
          generate:
            command: ["/bin/sh", "-c"]
            args: ["helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE -f values.yaml --include-crds > all.yaml && kustomize build"]
        - name: argocd-vault-plugin
          generate:
            command: ["argocd-vault-plugin"]
            args: ["generate", "./"]
        - name: argocd-vault-plugin-helm
          init:
            command: [sh, -c]
            args: ["helm dependency build"]
          generate:
            command: ["sh", "-c"]
            args: ["helm template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE ${helm_args} ${ARGOCD_ENV_PLUGIN_PARAMS} . --include-crds | argocd-vault-plugin generate -"]
        - name: argocd-vault-plugin-helm-kustomize
          init:
            command: [sh, -c]
            args: ["helm dependency build"]
          generate:
            command: ["sh", "-c"]
            args: ["helm template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE ${helm_args} ${ARGOCD_ENV_PLUGIN_PARAMS} . --include-crds > all.yaml && kustomize build | argocd-vault-plugin generate -"]

  repoServer:
    replicas: 2
    initContainers:
      - name: download-tools
        image: busybox:latest
        command: [sh, -c]
        env:
          - name: AVP_VERSION
            value: "1.12.0"
        args:
          - >-
            wget -O argocd-vault-plugin
            https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    volumes:
      - name: custom-tools
        emptyDir: {}
      - name: ssh-configs
        configMap:
          name: argocd-cm
          items:
            - key: sshConfigs
              path: config
    volumeMounts:
      - name: custom-tools
        mountPath: /usr/local/bin/argocd-vault-plugin
        subPath: argocd-vault-plugin
      - name: ssh-configs
        mountPath: /home/argocd/.ssh/
    envFrom:
      - secretRef:
          name: argocd-vault-plugin-credentials

    applicationSet:
      replicas: 2

  configs:
    knownHosts:
      data:
        ssh_known_hosts: |
          [gitea.ws.v3nc.org]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkGFzkGmuFarw1W53fDqArvfQfg52IFkXW7VCqfGBb2fdYgjPJvcOWbYEhABmOdpM9vJNZoQJabqaPIEYsSQrXxHxtft8e+sDqRH8D4BRkrA7Ql3WAn/zvPXEFbc81A8C/SUsZ6xGT19bSVE5yhw21+YeTxi4sJVPgVmVAjgVaKt+67WdLdccKzgNbGbhFF2eJoWKdcXbRVuXRlvVYCWSmqts5pZ6jt2voaxtV2dFY52jY8sFiq53DewW/c4EJypAMVTCr1quIIONq1tFPvLRffJ/W41u5OQgNEqROyIrRkisALxGvzszkxoc+hrQ5d+RGyaJPTiGRN/BMtHcGLhTDNurvoVDzjxnB70Zlf2pnjwI1WzXlwKn+Get8F0H2oOGdjAfAt+/i0wnelDqRppgzNzh1MKsblr5FISU2zPoNYmxp+tqYA+sK7o7/NQw+fpKsYPYa0yUP4TDdgRrHc+QqfL7hJe+nprVm6jIwkWN16RY8jfs148WJ9uV/ZOLBGI4s3qHFFc24HnYrx78eR6CfwluPCLJeR7Fu3qr+X5QaMuY0ocZ9QR9Y2WPwLtZN0IcmHfkhqML3E8qWHWTXxeBEZwQ8r5actzoxePy/7qEhaAY4KF6fekuM9X8noNO9B2P3ElgtiDKpvawNQ4Jj5IhU4Trfe7Zuf7S6u1e1IOos5w==
          [gitea.os.v3nc.org]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDjT0MLV6RwoLLGy7EgYP92ILFnbuyndNMD0/KxKzA18JPjb1FEtpjQ1cKeDt23AlbfbJFp62K/1e3Nzqlm2ZsndoPNVdRrP4VsKm7eDttjegT2DshgKvk2ZWpBtO5qOpf3FR0wWrNqvaibAjsVhDEhnfXHTgbAcn/l1ifxYJrLTWxXjkV03NtsYLRW4V76vz7LHP89dz/iI/FPyJeZKOBusr0EFMF03LXZyR7HLbFwAHQJQyh/zoo6PmwhQQKeW1nwYfxKE0ZACX4slxU0++u1MAdqX9cn2Bko4qsR27s2Uhy84G99/OwkCf8d2hfHJJ/FkQHeD9Q3WjwC3fsVKPO+Lh5j2S55MLrZ7vjyzo6+A2Vtgle6Antbw2CVPSTJ8BvcKAqIq8PsUv3FowS1r2lxB5AkUeJ9HUaMXzyLyK+zfEFRYzyjIf/feqezOnW4Ya7rgfnQIFbVbXsZDMCMTDs4dffqrnNGD6h+yrEiSkjIUzl9tSFAHmNwyu8y6/kcaICUVSTPAzhv2AiaDmeOR6jXD4+f4P0TgCR4O63vZnaegFOG+gAN++sk4UH5MVZOnxfKWOGXmjXKaWj4ku2seYyrqxQSME2SSnLCixSQX4GDLa/tbAj4SmoNxHHgvk9qKWWOyyaPOECWDqGnWO4mdr/2u1JsXzopshvfgfxjFU7RLQ==
          [gitea.ws.sh4ke.rocks]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpf9B1MzVjBq9R/BbbN16VVZmfpUQZSHwVUZghv+rIRR3PV5LtTFkTT+Tt665lYsWJjHWS3NpjO8PdXSYVlAD7x1OXI8LVQKPrbg04qI30EAk1xNwQJZGV1DL9NHMem+f2aXFNtV5745NFag4qqeBUVuWlClIuiqVj173LhkXT5VW7HW7p6OjBY3j6kxKuq4scMsb879O4m1JRq2RflwmEmSTTwLxWbgwh9gINbn8bZOymX/gOniblnqhDVjEKoj/EOXUqkI7LaQ8RacCKjp2drBr78pY/rVWluMq7F3eb+1SguaColLQC81V4Smtx+Vscnkw4fbOrEU9CDF+g//ZUp2CFXCHb/ev8piBixl4mlu5AFWxeEleYPxS/1WRdSIVuJ4mkpmQzqemXAJjq8xXTeRNIiAJp7/ZG8g7UAN8Dsf3sJ/GaSIv5cJPQuFbvdhVauA9xH5oc74A1AN7J5lFkrR8ko2UEHVhx0gULTC5DOb3NjkCsEawLQ2wVNCdpdy129Zqh3d/0URaIWglFkpQ5dyOTpnvvKBnhzYCCh0nozxl4XrrE3bz18KZBjHjcgivMMd6St5xzajS4/puQnJjSryYe3Diu+Ia7cHgZF/C8EzKIxmZzwAoJmdYNuvjkKp+OqvbvQxI9cNBBS8z21nvmtGjrlfcCC90lArE8tYi5JQ==
          [gitea.os.sh4ke.rocks]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRCQpuNNyqfjPxBtYKX3BLN3oGdL5Tm5BjyFKpBk6e7AbF5z/azZAWyBQKAufyjkvvC+TNmdqkLc1qG5feCs81UBFAgXmK3xYAuaJNAzbf3TP0NGgLD+gtzPm1ZEXy0lGN7pdfGm9e1GFDLDbvimijCPxbScnpnCGUHzT8CqdZVznxgzbaBlyMfq9SXk+HFL8uVxwJWI3h3PHe/KRXlnSrUtMpW/AXP/cD9NFZb+cE891as8ZNewz+Sx3a8SH1dMbXktqZxyY4hbIBZt1NABGHov/AzXsUWQ/+e2j1hh5C9fd6mIKGfgYGtoW8CdVd2YQIjNvYYIE5e7wJUNnfCmuzRTIDVbw7Iu62TQ1LXBvnDCLf/TloEGVTk6yiFrgmfw7qF5kaZQ74vdUg5cZGZAAoMW07ohgcA9RNV2XerDgi9wGR+75Y5qfJAnQCAZdQ9U7bW0bPWiK1Uq5zht3rfSKgnAmZ9KnxFbTcTQYnAHYKkQ1rmsF5uUmEc9oEyc2zJlC0PJutIh/7CHu655gweklqKlm6zZRU1UDeiefKwX62ANVS1qE28Xphw7yeqaAgsO56q09LOLO7TNkhxfH2FPOyuiNna88Bu7dj7yfabVrYzZ3+/XqNgjb2+csrlPh8WOiTFhgQa1gz79T/iMmGr/5RL+wK5Kipd5K3Rm8kOO3rIw==
          bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
          github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
          gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
          gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
          ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
          vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
