apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://g1tl4b.dynamic-dns.net/venc0r/k8s-apps.git
    path: hashicorp-vault
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
    # plugin:
    #   name: kustomized-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hashicorp-vault
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
