vault:
  server:
    auditStorage:
      enabled: true
      storageClass: csi
      size: 2Gi
    ha:
      enabled: true
      raft:
        enabled: true

    # This configures the Vault Statefulset to create a PVC for data
    # storage when using the file or raft backend storage engines.
    # See https://www.vaultproject.io/docs/configuration/storage/index.html to know more
    dataStorage:
      enabled: true
      # Size of the PVC created
      size: 2Gi
      # Name of the storage class to use.  If null it will use the
      # configured default Storage Class.
      storageClass: csi
