apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drone-https-cert
spec:
  commonName: {{ .Values.drone.env.DRONE_SERVER_HOST }}
  secretName: drone-https-cert
  dnsNames:
    - {{ .Values.drone.env.DRONE_SERVER_HOST }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
